### PR TITLE
Initial Renku jupyterlab extension

### PR DESCRIPTION
**Pull request by ciyer**
Does the first item under #29: creates a jupyterlab extension that provides a cheat sheet for the Renku CLI.

## Preview Image

image

## Test

You can test by launching an environment on this project:

https://dev.renku.ch/projects/cramakri/jl-extension/environments

### CODE REVIEW

**Review by lorenzo-cavazzi — CHANGES_REQUESTED** [review]
Very nice revamp of the plugin! The Cheat Sheet is indeed useful!

A couple of details I would address before merging:
1. The "Pod Info" page seems to be experimental. We could hide it for now.
2. The other plugins accessible from the toolbar on the left seems to have similar layout, leveraging the `jp-extensionmanager-xxx` classes. Would it make sense to make our menu more similar to that one?
I guess we need only a few things: spacing between entries, lighter color for the horizontal lines, smaller font.
Screenshot_20210105_115552

**Comment by ciyer** [comment]
Thanks for the feedback. The panel now looks like this.

image

Do you think that is better? I will also remove the PodInfo option and add it back in the next PR.

**Comment by ciyer** [comment]
I didn't redeploy, but this is what it looks like now:

image

#31 will provide an implementation of pod info.

Do you agree that it is ready to merge

**Review by lorenzo-cavazzi — APPROVED** [review]
> Do you agree that it is ready to merge?

Indeed it do! Let's revice this plugin :tada:

**Pull request merged**
